_target_: dataset.inpaint.InpaintDataModule
name: places2
data:
  train_dir: /data/places2/data_large
  val_dir: /data/places2/val_large
  test_dir: /data/places2/test_large
mask:
  train_dir: /data/mask_freeform
  val_dir: /data/mask_freeform
  test_dir: /data/mask_freeform
