defaults:
  - model: dfnet
  - loss: inpaint
  - optim: adam
  - scheduler: step
  - dataset: places2
  - pipeline: inpainter
  - hydra/job_logging: colorlog
  - hydra/hydra_logging: colorlog

pl_trainer:
  accelerator: ddp
  precision: 16
  amp_backend: native
  amp_level: O2
  profiler: simple
  weights_summary: top
  deterministic: true
  max_epochs: 20
  gpus: -1
  default_root_dir: ./

dataset:
  batch_size: 32
  num_workers: 4
  pin_memory: True

val_save:
  n_image_per_batch: 8
  n_save: 11

logging:
  - _target_: pytorch_lightning.loggers.TensorBoardLogger
    save_dir: .
    name: log
    version: tb
  - _target_: pytorch_lightning.loggers.CSVLogger
    save_dir: .
    name: log
    version: csv

callbacks:
  - _target_: pytorch_lightning.callbacks.ModelCheckpoint
    dirpath: log/checkpoints
    filename: '{epoch}-{step}-{val_loss:.2f}'
    # auto_insert_metric_name: false
    save_last: true
    monitor: 'val_loss'
    save_top_k: 2
    verbose: true

run_test: false
seed: 2021
find_unused_parameters: true

# debug / run
mode: run

hydra:
  run:
    dir: /outputs/${mode}/${dataset.data.name}/${model._target_}/${now:%Y-%m-%d_%H-%M-%S}