defaults:
  - model: dfnet
  - loss: inpaint
  - optim: adam
  - scheduler: step
  - dataset: places2
  - pipeline: inpainter

pl_trainer:
  accelerator: ddp
  precision: 16
  amp_backend: native
  amp_level: O2
  profiler: simple
  weights_summary: top
  deterministic: true
  max_epochs: 20
  gpus: -1
  default_root_dir: ./

dataset:
  batch_size: 32
  num_workers: 4
  pin_memory: True

val_save:
  n_image_per_batch: 8
  n_save: 10

run_test: false
seed: 2021
find_unused_parameters: true

hydra:
  run:
    dir: /outputs/${dataset.data.name}/${model._target_}/${now:%Y-%m-%d_%H-%M-%S}