defaults:
  - model: dfnet
  - loss: inpaint
  - optim: adamw
  - scheduler: cosine
  - dataset: [default, ahn4]
  - pipeline: inpainter
  - callbacks: [checkpoint, lr_monitor]
  - logging: null
  - mode: debug
  - pl_trainer: default
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog

val_save:
  n_image_per_batch: 8
  n_save: 11

run_test: false
seed: 2021

hydra:
  run:
    dir: /outputs/dfnet/${mode}/${dataset.name}/${model._target_}/${now:%Y-%m-%d_%H-%M-%S}
