defaults:
  - model: dfnet
  - loss: inpaint
  - optim: adamw
  - scheduler: cosine
  - dataset: [default, ahn4nl]
  - pipeline: inpainter
  - callbacks: [checkpoint, lr_monitor]
  - logging: null
  - mode: debug
  - pl_trainer: default
  - device: macbook
  - visual: default
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog

val_save:
  n_image_per_batch: 8
  n_save: 11

seed: 2021

custom: true
verbose: true

hydra:
  run:
    dir: ./outputs/${mode}/${dataset.name}/${now:%Y-%m-%d_%H-%M-%S}

  sweep:
    dir: ./outputs/multirun/${now:%Y-%m-%d_%H-%M-%S}
    subdir: ${hydra.job.override_dirname}
