checkpoint:
  _target_: pytorch_lightning.callbacks.ModelCheckpoint
  dirpath: log/checkpoints
  filename: '{epoch}-{step}-{val_loss:.2f}'
  # auto_insert_metric_name: false
  save_last: true
  monitor: 'val_loss'
  save_top_k: 2
  verbose: true
  mode: 'min'